#!/bin/sh
# postinst script for porteusbootscripts
#
# see: dh_installdeb(1)

#set -e

#. /usr/share/debconf/confmodule


mv -f -t /usr/bin /opt/tmp/snapmergepuppy /opt/tmp/save2flash /opt/tmp/wmpoweroff /opt/tmp/wmreboot
#mv -f -t /etc/init.d /opt/tmp/snapexit
mv -f -t /usr/local/bin /opt/tmp/snap-ex
mv -f -t /usr/local/bin /opt/tmp/mk-save.gtkdlg
mv -f -t /usr/bin /opt/tmp/makepfile.sh
rm -f /lib/systemd/system-shutdown/rc.local.shutdown
mv -f -t /etc /opt/tmp/rc.local.shutdown
mv -f -t /lib/systemd/system /opt/tmp/saveatshutdown.service

rm -rf /opt/tmp

if [ ! -f "/etc/systemd/system/multi-user.target.wants/saveatshutdown.service" ]; then
	systemctl enable saveatshutdown.service
#	systemctl start saveatshutdown.service
#	systemctl daemon-reload
echo "Recommended to reboot, to apply new systemd service saveatshutdown.service"
fi

if [ -x "/etc/init.d/snapexit" ]; then
	update-rc.d snapexit remove >/dev/null
fi







exit
